// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.151.1.0.1.27  $
// File generated on 2025/10/13 ¤U¤È 10:20:37 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files (x86)\Common Files\System\ado\msador28.tlb (1)
// LIBID: {00000300-0000-0010-8000-00AA006D2EA4}
// LCID: 0
// Helpfile: 
// HelpString: Microsoft ActiveX Data Objects Recordset 2.8 Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// Parent TypeLibrary:
//   (0) v1.0 EmulatorService, (D:\GitHub\BSP_emulator_service\BSP-2025\EmulatorService\EmulatorService.tlb)
// ************************************************************************ //
#ifndef   ADOR_OCXH
#define   ADOR_OCXH

#pragma option push -b -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0600)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "ADOR_TLB.h"
namespace Ador_tlb
{

// *********************************************************************//
// HelpString: Microsoft ActiveX Data Objects Recordset 2.8 Library
// Version:    2.8
// *********************************************************************//

};     // namespace Ador_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Ador_tlb;
#endif

#pragma option pop

#endif // ADOR_OCXH
